-- AD Electronics schema + RPC helpers for Supabase
begin;

create table if not exists public.customers (
  phone varchar(20) primary key,
  name varchar(100) not null,
  address text,
  id_card_no varchar(50)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_phone varchar(20) not null,
  customer_name varchar(100) not null,
  overall_time integer check (overall_time is null or overall_time > 0),
  items text not null,
  total numeric(10,2) not null check (total >= 0),
  advance_payment numeric(10,2) not null default 0 check (advance_payment >= 0),
  remaining_balance numeric(10,2) not null check (remaining_balance >= 0),
  purchase_date date not null,
  next_payment_date date,
  is_complete boolean not null default false,
  created_at timestamptz not null default now(),
  constraint orders_customer_phone_fkey
    foreign key (customer_phone)
    references public.customers(phone)
    on update cascade
    on delete cascade
);

alter table if exists public.orders
  add column if not exists overall_time integer;

alter table if exists public.orders
  drop constraint if exists orders_overall_time_check;

alter table if exists public.orders
  add constraint orders_overall_time_check
  check (overall_time is null or overall_time > 0);

alter table if exists public.orders
  drop constraint if exists orders_customer_phone_fkey;

alter table if exists public.orders
  add constraint orders_customer_phone_fkey
  foreign key (customer_phone)
  references public.customers(phone)
  on update cascade
  on delete cascade;

create table if not exists public.order_payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  amount numeric(10,2) not null check (amount > 0),
  payment_date timestamptz not null default now(),
  payment_source text not null default 'installment'
    check (payment_source in ('advance', 'installment')),
  constraint order_payments_order_id_fkey
    foreign key (order_id)
    references public.orders(id)
    on delete cascade
);

create index if not exists idx_customers_name on public.customers(name);
create index if not exists idx_orders_customer_phone on public.orders(customer_phone);
create index if not exists idx_orders_purchase_date on public.orders(purchase_date desc, id desc);
create index if not exists idx_orders_status_next_payment on public.orders(is_complete, next_payment_date);
create index if not exists idx_order_payments_order_date on public.order_payments(order_id, payment_date);

create or replace function public.update_customer_and_orders(
  p_current_phone varchar,
  p_new_phone varchar,
  p_name varchar,
  p_address text,
  p_id_card_no varchar
)
returns void
language plpgsql
as $$
declare
  v_exists boolean;
begin
  if p_name is null or btrim(p_name) = '' then
    raise exception 'NAME_REQUIRED';
  end if;

  if p_new_phone is null or btrim(p_new_phone) = '' then
    raise exception 'PHONE_REQUIRED';
  end if;

  select exists(
    select 1 from public.customers c where c.phone = p_current_phone
  ) into v_exists;

  if not v_exists then
    raise exception 'CUSTOMER_NOT_FOUND';
  end if;

  if p_new_phone <> p_current_phone then
    select exists(
      select 1 from public.customers c where c.phone = p_new_phone
    ) into v_exists;

    if v_exists then
      raise exception 'PHONE_ALREADY_EXISTS';
    end if;

    insert into public.customers (phone, name, address, id_card_no)
    values (p_new_phone, p_name, p_address, p_id_card_no);

    update public.orders
    set
      customer_phone = p_new_phone,
      customer_name = p_name
    where customer_phone = p_current_phone;

    delete from public.customers
    where phone = p_current_phone;
  else
    update public.customers
    set
      name = p_name,
      address = p_address,
      id_card_no = p_id_card_no
    where phone = p_current_phone;

    update public.orders
    set customer_name = p_name
    where customer_phone = p_current_phone;
  end if;
end;
$$;

create or replace function public.create_order_with_advance(
  p_customer_phone varchar,
  p_overall_time integer,
  p_items text,
  p_total numeric,
  p_advance_payment numeric,
  p_purchase_date date,
  p_next_payment_date date,
  p_is_complete boolean
)
returns bigint
language plpgsql
as $$
declare
  v_customer_name varchar(100);
  v_order_id bigint;
  v_advance numeric(10,2);
  v_remaining numeric(10,2);
begin
  if p_customer_phone is null or btrim(p_customer_phone) = '' then
    raise exception 'CUSTOMER_PHONE_REQUIRED';
  end if;

  if p_items is null or btrim(p_items) = '' then
    raise exception 'ITEMS_REQUIRED';
  end if;

  if p_total is null then
    raise exception 'TOTAL_REQUIRED';
  end if;

  if p_purchase_date is null then
    raise exception 'PURCHASE_DATE_REQUIRED';
  end if;

  select c.name
  into v_customer_name
  from public.customers c
  where c.phone = p_customer_phone;

  if v_customer_name is null then
    raise exception 'CUSTOMER_NOT_FOUND';
  end if;

  v_advance := coalesce(p_advance_payment, 0)::numeric(10,2);
  v_remaining := greatest(round((p_total - v_advance)::numeric, 2), 0)::numeric(10,2);

  insert into public.orders (
    customer_phone,
    customer_name,
    overall_time,
    items,
    total,
    advance_payment,
    remaining_balance,
    purchase_date,
    next_payment_date,
    is_complete
  )
  values (
    p_customer_phone,
    v_customer_name,
    p_overall_time,
    p_items,
    round(p_total::numeric, 2),
    v_advance,
    v_remaining,
    p_purchase_date,
    p_next_payment_date,
    coalesce(p_is_complete, false)
  )
  returning id into v_order_id;

  if v_advance > 0 then
    insert into public.order_payments (order_id, amount, payment_date, payment_source)
    values (v_order_id, v_advance, p_purchase_date::timestamptz, 'advance');
  end if;

  return v_order_id;
end;
$$;

create or replace function public.apply_order_payment(
  p_order_id bigint,
  p_amount numeric,
  p_next_payment_date date
)
returns table (
  remaining_balance numeric(10,2),
  is_complete boolean
)
language plpgsql
as $$
declare
  v_current_remaining numeric(10,2);
  v_current_complete boolean;
  v_updated_remaining numeric(10,2);
  v_is_complete boolean;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception 'INVALID_PAYMENT_AMOUNT';
  end if;

  select o.remaining_balance, o.is_complete
  into v_current_remaining, v_current_complete
  from public.orders o
  where o.id = p_order_id
  for update;

  if not found then
    raise exception 'ORDER_NOT_FOUND';
  end if;

  if v_current_complete then
    raise exception 'ORDER_ALREADY_COMPLETE';
  end if;

  v_updated_remaining := greatest(round((v_current_remaining - p_amount)::numeric, 2), 0)::numeric(10,2);
  v_is_complete := (v_updated_remaining <= 0);

  update public.orders
  set
    remaining_balance = v_updated_remaining,
    next_payment_date = p_next_payment_date,
    is_complete = v_is_complete
  where id = p_order_id;

  insert into public.order_payments (order_id, amount, payment_date, payment_source)
  values (p_order_id, round(p_amount::numeric, 2), now(), 'installment');

  return query
  select v_updated_remaining, v_is_complete;
end;
$$;

commit;
